name: Deploy stack via Makefile

on:
  workflow_dispatch:
    inputs:
      make_target:
        description: 'Comando Makefile para executar (all, package, upload, deploy, test, destroy)'
        required: true
        default: 'all'
      DESTROY_AFTER:
        description: 'Destruir ambiente após execução? (true/false)'
        required: false
        default: 'false'

jobs:
  deploy:
    name: Deploy via Makefile
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      STACK_NAME: ${{ vars.STACK_NAME }}
      BUCKET_NAME: ${{ vars.BUCKET_NAME }}
      ZIP_NAME: ${{ vars.ZIP_NAME }}
      TEMPLATE_PATH: ${{ vars.TEMPLATE_PATH }}
      PROJECT_NAME: ${{ vars.PROJECT_NAME }}
      FUNCTION_DIR: ${{ vars.FUNCTION_DIR }}
      DESTROY_AFTER: ${{ github.event.inputs.DESTROY_AFTER }}

    steps:
      - name: 🔻 Checkout código-fonte
        uses: actions/checkout@v4

      - name: 📦 Instalar zip (caso necessário)
        if: ${{ github.event.inputs.make_target != 'destroy' }}
        run: sudo apt-get install zip -y

      - name: 🔐 Configurar credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: ⚙️ Executar Makefile
        run: |
          echo "Executando Makefile com comando: ${{ github.event.inputs.make_target }}"
          make ${{ github.event.inputs.make_target }}

      - name: 🧹 Destruir ambiente de teste (se ativado)
        if: ${{ github.event.inputs.make_target != 'destroy' && github.event.inputs.DESTROY_AFTER == 'true' }}
        run: make destroy
